### ISSUE TITLE
Default values in config template

### ISSUE THREAD

**Issue by kumaya** [infobloxopen/atlas-cli#55]
We need:
https://github.com/infobloxopen/atlas-cli/blob/122ae2e4a27bb94071328903a78db0eeb42b6d54/atlas/config.gotmpl#L69-L70

and https://github.com/infobloxopen/atlas-cli/blob/122ae2e4a27bb94071328903a78db0eeb42b6d54/atlas/config.gotmpl#L128-L129

defined in [config template](https://github.com/infobloxopen/atlas-cli/blob/master/atlas/templates/cmd/server/config.go.gotmpl)

Though README.md indicates that we need to copy `config.go` for usage but I see active development in https://github.com/infobloxopen/atlas-cli/blob/master/atlas/templates/cmd/server/config.go.gotmpl

**Comment by brocwoodworthIBLX** [comment]
should be fixed with https://github.com/infobloxopen/atlas-cli/pull/56
